.\" Manpage for hello
.TH hello 1 "May 25, 2025" "1.0" "build-deb-hello manual"
.SH NAME
hello \- A simple hello-world script
.SH SYNOPSIS
.B hello
.SH DESCRIPTION
hello is a simple script that prints "Hello, world!" to the console.
.SH AUTHOR
Matthew Elgert <mdelgert@yahoo.com>
.SH COPYRIGHT
Copyright 2025 Matthew Elgert. Licensed under the MIT License.
