name: Build Debian package

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up build dependencies
        run: sudo apt-get update && sudo apt-get install -y devscripts debhelper
      - name: Build deb
        uses: jtdor/build-deb-action@v3
        with:
          source-root: .
